if: tag IS blank
language: java
script: ./gradlew shadowJar
before_deploy:
    # Set up git user name and tag this commit
    - git config --local user.name "nelenkov"
    - export TRAVIS_TAG=${TRAVIS_TAG:-${TRAVIS_BRANCH}-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
    - git tag -f $TRAVIS_TAG
deploy:
    provider: releases
    api_key: "$GH_TOKEN"
    file: build/libs/abe.jar
    skip_cleanup: true
    on:
      branch: master
